### ISSUE TITLE
The SDK UI appears for a few seconds and then disappears

### ISSUE THREAD

**Issue by HC2970** [OrfeasZ/ZHMModSDK#81] opened 2023-10-27 18:40 UTC
I am not running and third party UI's, I have turned off discord and any other background apps. When I press the ` button it works as if the UI was there but it isn't visible (The mouse appears on screen and the game is unclickable) I am on epic games with windows 11.

**Comment by luxmanifestus** [comment] 2023-11-02 04:28
+1. I posted my problem as well. The UI menu seems to be hidden by the Hitman application (it covers over it). I have disabled all overlays and it persists.

**Comment by luxmanifestus** [comment] 2023-11-04 23:50
Got this tip in my post. It worked for me. "Not sure if it's how it works but you can try adding the mods you want to mods.ini directly by using the scheme in the file. For instance, if you are trying to added Freelancer Variations but find that the UI disappears too fast you can try adding [freelancervariations] followed by a new line. Essentially, take the name of the dll file, put it in lowercase, remove .dll, then add the brackets. Should look like this: image

Edit: Though, if you are having UI issues still I wouldn't recommend enabling DebugMod or AdvancedRating since they are unusable without the UI. You should find use for everything else here though."

**Comment by OrfeasZ** [comment] 2023-11-10 21:46
Duplicate of #77. Please check the last comment there for more info.

**Closed by OrfeasZ** 2023-11-10 21:46 UTC
