### ISSUE TITLE
SDK UI renderer causes crashes and freezes

### ISSUE THREAD

**Issue by tymnasium** [OrfeasZ/ZHMModSDK#37] opened 2023-01-28 17:18 UTC
I installed SDK release 1.7 to the retail folder. Whenever I try to launch the game through steam, it cuts to black like it’s launching, and then crashes quickly back to desktop. 

Also there isn’t a mods.ini file in the release. Does it generate if the sdk successfully launches with the game? Trying to play the new freelancer mod but the SDK is preventing my game from working. It’s only when I remove the files that the game launches.

**Comment by OrfeasZ** [comment] 2023-01-28 17:24
Do you have any overlay software other than Steam's, like RTSS, Discord, ROG, etc? If so, try turning them off and see if that helps. Otherwise, paste `%LOCALAPPDATA%\CrashDumps` in your windows explorer file path bar to go to that folder, look for the newest file named `HITMAN3.exe.XXXXX.dmp`, and e-mail that to me to the e-mail found on [my profile](https://github.com/OrfeasZ) (you can also post it here but keep in mind that it might contain sensitive information, like your windows username and temporary steam / egs / whatever platform you're using auth tokens).

You can also look at #36. Maybe it's related to your issue too?

The `mods.ini` file is created after successful launch, yes.

**Comment by tymnasium** [comment] 2023-01-28 18:25
I've emailed you 3 dmp files. According to windebug it seems to reach an 8000003 breakpoint with the exe file but you might have a better idea.

**Comment by tymnasium** [comment] 2023-01-28 18:44
Seems to be related to dinput8.dll - when I remove these files - the game runs. But sdk still doesn't launch or deploy.

**Comment by Skullfox** [comment] 2023-01-28 19:02
Changing the compatibility `hitman3.exe` to `windows vista` solved my startup crashes.

**Comment by tymnasium** [comment] 2023-01-28 19:05
> Changing the compatibility `hitman3.exe` to `windows vista` solved my startup crashes.

This fixed it. You are a genius!

**Comment by OrfeasZ** [comment] 2023-01-28 19:06
Re-opening this since I actually need to figure out what's going on and fix this.

**Comment by doctorthoss** [comment] 2023-01-29 03:30
having the same issue here but the compatibility mode thing did *not* fix it. seeing similar reports from people in the comments for this mod here: https://www.nexusmods.com/hitman3/mods/437?tab=posts

**Comment by doctorthoss** [comment] 2023-01-30 02:19
for the record this is happening with only the skip intro mod enabled, no other mods are enabled via SDK or via simple mod framework. I've tried  removing even the skip intro mod but it stills happens

**Comment by doctorthoss** [comment] 2023-01-30 02:27
for the record this is happening with only the skip intro mod enabled, no other mods are enabled via SDK or via simple mod framework. I've tried removing even the skip intro mod but it still happens.

here's the entirety of the debug window log if that's useful
Successfully located function 'ZActor_OnOutfitChanged' at address '0x140184630'.
Successfully located function 'ZActor_ReviveActor' at address '0x1401770f0'.
Successfully located function 'ZDynamicObject_ToString' at address '0x14006f420'.
Successfully located function 'ZHM5BaseCharacter_ActivateRagdoll' at address '0x1401132b0'.
Successfully located function 'GetCurrentCamera' at address '0x14143fa10'.
Successfully located function 'ZSpatialEntity_WorldTransform' at address '0x140f17d10'.
Successfully located function 'ZEngineAppCommon_CreateFreeCamera' at address '0x140059a40'.
Successfully located function 'ZCameraManager_GetActiveRenderDestinationEntity' at address '0x141214170'.
Successfully located function 'ZInputAction_Analog' at address '0x140f5f750'.
Successfully located function 'ZInputAction_Digital' at address '0x140f5f370'.
Successfully located function 'ZPlayerRegistry_GetLocalPlayer' at address '0x14005b360'.
Successfully located function 'ZHM5InputManager_GetInputControlForLocalPlayer' at address '0x1400d2eb0'.
Successfully located function 'ZResourceManager_UninstallResource' at address '0x1413bb8d0'.
Successfully located function 'ZEntityManager_NewEntity' at address '0x140ef9920'.
Successfully located function 'ZSpatialEntity_UnknownTransformUpdate' at address '0x140f16b20'.
Successfully located function 'ZHitman5_SetOutfit' at address '0x14034e440'.
Successfully located function 'ZActor_SetOutfit' at address '0x140183f00'.
Successfully located function 'ZItemSpawner_RequestContentLoad' at address '0x140daac70'.
Successfully located function 'ZCharacterSubcontrollerInventory_AddDynamicItemToInventory' at address '0x1407d0ce0'.
Successfully located function 'ZResourceContainer_GetResourceReferences' at address '0x1413b2b50'.
Successfully located global 'GameLoopManager' at address 0x1431a7380.
Successfully located global 'TypeRegistry' at address 0x1429bdc10.
Successfully located global 'GameTimeManager' at address 0x1431a6ea0.
Successfully located global 'Hitman5Module' at address 0x1446a8fc0.
Successfully located global 'GameContext' at address 0x1429bdc60.
Successfully located global 'ActorManager' at address 0x1429bdcc0.
Successfully located global 'NextActorId' at address 0x1429c2340.
Successfully located global 'MemoryManager' at address 0x1429bdbf0.
Successfully located global 'RenderManager' at address 0x1433900a0.
Successfully located global 'ApplicationEngineWin32' at address 0x1429bdbd0.
Successfully located global 'GameUIManager' at address 0x143177080.
Successfully located global 'EntityManager' at address 0x1431a6f20.
Successfully located global 'GameStatsManager' at address 0x143173ba0.
Successfully located global 'CameraManager' at address 0x14338dfe0.
Successfully located global 'PlayerRegistry' at address 0x14317a2e0.
Successfully located global 'InputManager' at address 0x142a478e0.
Successfully located global 'ResourceManager' at address 0x143991b20.
Successfully located global 'ResourceContainer' at address 0x14317a2d0.
Successfully located global 'CollisionManager' at address 0x143175a50.
Successfully located global 'ContentKitManager' at address 0x142a52100.
Successfully located global 'HM5ActionManager' at address 0x142a52160.
Adding thread 6196 to the list of threads to suspend.
Adding thread 1404 to the list of threads to suspend.
Adding thread 7552 to the list of threads to suspend.
Adding thread 12100 to the list of threads to suspend.
Adding thread 13200 to the list of threads to suspend.
Adding thread 8964 to the list of threads to suspend.
Adding thread 12932 to the list of threads to suspend.
Suspending 7 threads.
Successfully installed detour for hook 'ZActor_ZActor' at address 0x14016e520.
Successfully installed detour for hook 'ZEntitySceneContext_LoadScene' at address 0x1400c82d0.
Successfully installed detour for hook 'ZEntitySceneContext_ClearScene' at address 0x1400c7990.
Successfully installed detour for hook 'ZUpdateEventContainer_AddDelegate' at address 0x140eefca0.
Successfully installed detour for hook 'ZUpdateEventContainer_RemoveDelegate' at address 0x140eefda0.
Successfully installed detour for hook 'Engine_Init' at address 0x14004f280.
Successfully installed detour for hook 'ZKnowledge_SetGameTension' at address 0x1401a6fd0.
Successfully installed detour for hook 'GetApplicationOptionBool' at address 0x1400474a0.
Successfully installed detour for hook 'ZApplicationEngineWin32_OnMainWindowActivated' at address 0x14004ac10.
Successfully installed detour for hook 'ZApplicationEngineWin32_MainWindowProc' at address 0x14004adb0.
Successfully installed detour for hook 'SetPropertyValue' at address 0x140f14bd0.
Successfully installed detour for hook 'SignalOutputPin' at address 0x140f14690.
Successfully installed detour for hook 'SignalInputPin' at address 0x140f14790.
Successfully installed detour for hook 'D3D12CreateDevice' at address 0x7ffea8806af0.
Successfully installed detour for hook 'Check_SSL_Cert' at address 0x140fe7680.
Successfully installed detour for hook 'ZApplicationEngineWin32_OnDebugInfo' at address 0x14006c650.
Successfully installed detour for hook 'ZKeyboardWindows_Update' at address 0x140f6c270.
Successfully installed detour for hook 'ZPackageManagerPackage_ZPackageManagerPackage' at address 0x14139d1b0.
Successfully installed detour for hook 'ZGameLoopManager_ReleasePause' at address 0x140eef470.
Successfully installed detour for hook 'ZGameUIManagerEntity_TryOpenMenu' at address 0x140a01030.
Successfully installed detour for hook 'ZGameStatsManager_SendAISignals01' at address 0x1401657a0.
Successfully installed detour for hook 'ZGameStatsManager_SendAISignals02' at address 0x140165470.
Successfully installed detour for hook 'ZAchievementManagerSimple_OnEventReceived' at address 0x140a1d780.
Successfully installed detour for hook 'ZAchievementManagerSimple_OnEventSent' at address 0x140a1bb10.
Successfully installed detour for hook 'ZInputAction_Digital' at address 0x140f5f370.
Successfully installed detour for hook 'ZInputAction_Analog' at address 0x140f5f750.
Successfully installed detour for hook 'ZEntityManager_DeleteEntities' at address 0x140efac10.
Successfully installed detour for hook 'ZEntityManager_ActivateEntity' at address 0x140efa5b0.
Successfully installed detour for hook 'Http_WinHttpCallback' at address 0x140fe62c0.
Successfully installed detour for hook 'ZHttpResultDynamicObject_OnBufferReady' at address 0x140fd5cc0.
Successfully installed detour for hook 'ZTemplateEntityFactory_ConfigureEntity' at address 0x140f2b8a0.
Successfully installed detour for hook 'ZCppEntityFactory_ConfigureEntity' at address 0x140ef8290.
Successfully installed detour for hook 'ZBehaviorTreeEntityFactory_ConfigureEntity' at address 0x1405c82e0.
Successfully installed detour for hook 'ZAudioSwitchEntityFactory_ConfigureEntity' at address 0x140e501a0.
Successfully installed detour for hook 'ZAspectEntityFactory_ConfigureEntity' at address 0x140ef52f0.
Successfully installed detour for hook 'ZRenderMaterialEntityFactory_ConfigureEntity' at address 0x1411bf4d0.
Resuming 7 suspended threads.
Looking for mods in 'C:\Program Files (x86)\Steam\steamapps\common\HITMAN 3\retail\mods'...
[D3D12Hooks] Locating D3D12 vtable addresses.
[D3D12Hooks] Could not get debug interface with error: 887A002D
[D3D12Hooks] Enabling D3D12 breadcrumbs and page fault reporting.
[D3D12Hooks] Creating D3D12 device.
[D3D12Hooks] Creating command queue.
[D3D12Hooks] Creating command allocator.
[D3D12Hooks] Creating command list.
[D3D12Hooks] Creating fake window for swap chain.
[D3D12Hooks] Creating swap chain.
[D3D12Hooks] Located all D3D12 vtable addresses.
[D3D12Hooks] Cached vtable addresses in shared memory.
Adding thread 13328 to the list of threads to suspend.
Adding thread 6196 to the list of threads to suspend.
Adding thread 1404 to the list of threads to suspend.
Adding thread 7552 to the list of threads to suspend.
Adding thread 12100 to the list of threads to suspend.
Adding thread 13200 to the list of threads to suspend.
Adding thread 8964 to the list of threads to suspend.
Adding thread 12932 to the list of threads to suspend.
Adding thread 3876 to the list of threads to suspend.
Adding thread 16552 to the list of threads to suspend.
Adding thread 3552 to the list of threads to suspend.
Adding thread 12748 to the list of threads to suspend.
Adding thread 1140 to the list of threads to suspend.
Adding thread 1912 to the list of threads to suspend.
Adding thread 15392 to the list of threads to suspend.
Adding thread 2920 to the list of threads to suspend.
Adding thread 2036 to the list of threads to suspend.
Adding thread 2812 to the list of threads to suspend.
Adding thread 15824 to the list of threads to suspend.
Adding thread 7020 to the list of threads to suspend.
Adding thread 3976 to the list of threads to suspend.
Adding thread 9144 to the list of threads to suspend.
Adding thread 16044 to the list of threads to suspend.
Suspending 23 threads.
Successfully installed detour for D3D12 vtable hook address 0x7ffe8e591910.
Successfully installed detour for D3D12 vtable hook address 0x7ffe8e592040.
Successfully installed detour for D3D12 vtable hook address 0x7ffe8e58a9a0.
Successfully installed detour for D3D12 vtable hook address 0x7ffe5c8ae9a0.
Resuming 23 suspended threads.
Installed D3D hooks.

**Comment by doctorthoss** [comment] 2023-01-30 02:59
And one last comment as I've been testing some random stuff out. No idea if this is useful so apologies if not.

If I try to launch the game with only dinput8.dll & dinput8.pdb from the SDK in the retail folder, _without_ either of the ZHMModSDK files, I get this error pop-up when the game fails to launch. With all the files in place I don't get an error, the game just never launches. 

![image](https://user-images.githubusercontent.com/81924327/215378217-c5b93485-b603-479a-8c85-927e4ac7ff1c.png)

**Comment by OrfeasZ** [comment] 2023-01-30 03:00
That's normal. Both `dinput8.dll` and `ZHMModSDK.dll` are required for the SDK to work.

**Comment by doctorthoss** [comment] 2023-01-30 03:02
> That's normal. Both `dinput8.dll` and `ZHMModSDK.dll` are required for the SDK to work.

copy that, figured as much, I was just trying random weird troubleshoots after none of my fiddling in the compatibility window for hitman3.exe helped

**Comment by OrfeasZ** [comment] 2023-01-30 03:03
Do you have a controller plugged in? Does unplugging it help at all?

**Comment by doctorthoss** [comment] 2023-01-30 03:05
> Do you have a controller plugged in? Does unplugging it help at all?

Nope, I've tried all the fixes I've seen mentioned. No controller plugged in, no external overlay like steam/nvidia/RTSS/etc running, no controllers plugged in

**Comment by tymnasium** [comment] 2023-01-30 19:23
Just everything in the bin folder or should I add all of the other folders in /retail? Like dragging the contents of "include" into the /retail folder etc.

**Comment by tymnasium** [comment] 2023-01-30 19:27
Quick update - that artifact download works. My game now runs without needing to be in compatibility mode! I can finally have DLSS again.

**Comment by OrfeasZ** [comment] 2023-01-31 02:00
@tymnasium @doctorthoss could you post your pc specs, os version, and gpu driver version? It would help be with identifying the issue with the UI rendering.

**Comment by siteod** [comment] 2023-01-31 03:36
The no UI version fixes all the controller and crash/freeze issues for me! Maybe next version you can add another option to not display the warning box every boot

**Comment by OrfeasZ** [comment] 2023-01-31 03:37
@siteod That is intentional since this is only temporary and I don't want people forgetting to turn it off once it's fixed. Can you please post what I asked for above?

**Comment by siteod** [comment] 2023-01-31 03:38
sorry, tried to stealth edit lol

win11
intel i7-9750h
32gb ram
nvidia 1660ti driver version 528.24

**Comment by piepieonline** [comment] 2023-01-31 08:45
noui is fixing it for me too, though I get inconsistent successful launches without it.
Steam and Gamepass
Win10
AMD Ryzen 5 5600XT
32gb ram
AMD Radeon RX 5600XT (Driver version 22.11.2)
No controllers attached (Unless it's picking up the VR controllers, which it.. might?)

**Comment by doctorthoss** [comment] 2023-01-31 16:24
> @tymnasium @doctorthoss could you post your pc specs, os version, and gpu driver version? It would help me with identifying the issue with the UI rendering.

i5 9600k
GTX 3070
32GB RAM
Windows 10 22H2 Build 19045.2486
GPU Driver 528.24 (latest stable at time of post)

**Comment by tymnasium** [comment] 2023-01-31 16:28
> @tymnasium @doctorthoss could you post your pc specs, os version, and gpu driver version? It would help me with identifying the issue with the UI rendering.

i9 12900K
RTX 4080
64 GB RAM
Windows 11 22621.1194
GPU Driver 528.24

**Comment by OrfeasZ** [comment] 2023-02-08 20:50
@siteod @piepieonline @doctorthoss @tymnasium @VoodooHillbilly and everyone else who was having crashing / freezing / performance issues, can you try the latest build from [here](https://github.com/OrfeasZ/ZHMModSDK/actions/runs/4128166509)? I've made a few changes to hopefully address these issues but I'd greatly appreciate your help in testing if they're actually resolved for you.

Before testing make sure to remove the `noui = true` from your `mods.ini` and once in-game check that the SDK UI is working by pressing the `~` (or in some keyboards `^`) key (under `Escape`).

**Comment by OrfeasZ** [comment] 2023-02-09 00:14
@VoodooHillbilly is this on Windows or on Linux? I haven't really tested on linux so can't attest to how that would work. The menu becoming unusable after pressing `~` is normal, as focus is normally given to the SDK UI (which you don't see). You can just press it again to turn it off.

**Comment by ajseavey** [comment] 2023-02-11 04:03
No UI fixed it for me. 

Win 10
Nvidia RTX2070 Super, Driver version 528.49 
AMD R7 3700X
32 GB RAM
Steam Version
2 Monitors
Disconnected controller
VR headset connected (Also get the VR warning in-game FWIW)

**Comment by OrfeasZ** [comment] 2023-02-11 13:31
That's normal when using the Freelancer Variations as it needs to be updated to use the latest version of the SDK (which will happen after I've confirmed the issue is solved and release an update). Does new version without any mods and without `noui` cause any issues for you?

**Comment by ajseavey** [comment] 2023-02-11 14:20
I'm 99% sure I'm currently running the release build of the latest version posted in this thread. Played it with the Freelancer Variations mod with the UI last night and it worked. Just removed the Freelancer Variations mod and the game still works without the `noui` flag.

**Comment by RGB00255** [comment] 2023-02-11 14:35
The UI still does not work with RTSS but it's definitely a bit better now since the game does not crash anymore. But, pressing the button to open the UI just shows the mouse and nothing else. Works fine if I am not RTSS though.

**Comment by OrfeasZ** [comment] 2023-02-11 16:22
@RGB00255 RTSS has been causing issues for me as well when in anything but "Low" application detection mode (most of the time). I'm now tracking this separately in #39.

**Comment by OrfeasZ** [comment] 2023-02-20 14:13
Fixed in [v1.8.0](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v1.8.0). Keep in mind that Freelancer Variations (and similar mods) will need to be updated as well. Using old versions might result in incompatibilities / crashes.

**Closed by OrfeasZ** 2023-02-20 14:13 UTC
Labels: bug, help wanted
