### ISSUE TITLE
Cant spawn assets!

### ISSUE THREAD

**Issue by FINDERSSS** [OrfeasZ/ZHMModSDK#89] opened 2024-01-13 01:27 UTC
When trying to spawn assets i just cant none show up and if i type the name in anyways and try nothing happens please fix! thank you

**Comment by OrfeasZ** [comment] 2024-01-19 13:40
Can you try with the latest build from here? https://github.com/OrfeasZ/ZHMModSDK/actions/runs/7370673325

**Comment by Richard-Creasman** [comment] 2024-01-24 21:43
After trying to replicate on the newest release candidate linked, the assets menu works as intended after entering anything into the blank. Thanks for the fix!

**Comment by OrfeasZ** [comment] 2024-02-01 11:31
Fixed in [v2.0.0-rc.2](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v2.0.0-rc.2).

**Closed by OrfeasZ** 2024-02-01 11:31 UTC
