### ISSUE TITLE
Third-party overlays can override the SDK's causing no UI to be rendered

### ISSUE THREAD

**Issue by Vasilaki08** [OrfeasZ/ZHMModSDK#39] opened 2023-01-29 12:24 UTC
Some third-party overlays can override the SDK's UI hooks, resulting in the SDK UI not being rendered / visible.

Overlays that break the UI:
- [ ] MangoHUD
- [ ] RTSS

**Original comment:**

Someone already asked this, but the dialog doesn't appear for me. I'm running the latest version of the game (3.140.0) on Epic Games, but it still doesn't appear. I followed the steps completely. Did it twice, still doesn't appear. Any way I can fix this? Thanks in advance!

**Comment by OrfeasZ** [comment] 2023-01-30 02:16
Does anything happen if you press the `~` key once in the main menu?

**Comment by Vasilaki08** [comment] 2023-02-01 16:12
> Does anything happen if you press the `~` key once in the main menu?

My cursor appears and I can't click on anything.

**Comment by OrfeasZ** [comment] 2023-02-01 16:31
What are your pc specs, OS version, and GPU driver version?

**Comment by Vasilaki08** [comment] 2023-02-01 16:56
> What are your pc specs, OS version, and GPU driver version?

Windows 10 the newest update and the latest NVIDIA driver update.

**Comment by OrfeasZ** [comment] 2023-02-06 15:10
I've identified an issue where some programs will overwrite the sdk's overlay renderer, which is probably what's happening here. I'll let you know once I have an update you can try.

**Comment by OrfeasZ** [comment] 2023-02-08 20:52
@Vasilaki08 can you try with the latest build from [this](https://github.com/OrfeasZ/ZHMModSDK/issues/37#issuecomment-1423222632) comment and see if this resolves your issue?

**Comment by MaxSSD** [comment] 2023-02-24 19:32
I found that the GeForce Experience overlay seems to crash with Freelancer Variations mod just before the map loading progress finishes. I read [here](https://www.nexusmods.com/hitman3/mods/437?tab=description) in known issues that it's an SDK bug. Do you have an idea of what could be the cause? I did not peruse the repo just yet but I'd say it's likely that the overlay ordering may be overlapping.

**Comment by OrfeasZ** [comment] 2023-02-25 11:59
@MaxSSD does it also crash with the Freelancer Variation mods disabled?

**Comment by MaxSSD** [comment] 2023-02-26 03:32
I will do a few tests on that shortly. 

I found that adding a few lines to set HWND of the game window, may fix the issues conflicting with other sdks.

```c
void setZOrderOnTop(HWND hWnd)
{
    SetWindowPos(hWnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
}
```
In DllMain 
```c
    // we set it to the HWND of the game's window.
    auto s_GameWindow = FindWindowW(L"UnrealWindow", nullptr);

    // set the window's z-order so that the console appears on top of the game
    SetWindowPos(s_GameWindow, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);

    return true;
}
```

**Comment by MaxSSD** [comment] 2023-02-26 08:43
> @MaxSSD does it also crash with the Freelancer Variation mods disabled?

I played a campaign where in the 1st part, the game was launched by GeForce Experience with no variations mods, and all was good. 

2nd part was with GeForce experience and mods, all was good. 

3rd part was with the steam launch and no variation mods, all was good.

4th part was with the steam launch and with the mod and that's when it crashed, stopped crashing when I closed the Nvidia processes.

When I had the Steam controller on it was crashing every other game loading.

**Comment by OrfeasZ** [comment] 2023-11-10 22:35
This might be addressed in the latest build. See last comment in #77 for details.

**Closed by OrfeasZ** 2023-11-10 22:35 UTC
Labels: bug

**Comment by coryzibell** [comment] 2023-11-22 22:10
> @Vasilaki08 can you try with the latest build from [this](https://github.com/OrfeasZ/ZHMModSDK/issues/37#issuecomment-1423222632) comment and see if this resolves your issue?

I can confirm this build works on my end after experiencing this issue. No crashes, Freelancer Variations working fine. Thanks!
