### ISSUE TITLE
The game permanently freezes when I try to stop recording with Nvidia Shadowplay

### ISSUE THREAD

**Issue by LikonLikon** [OrfeasZ/ZHMModSDK#14] opened 2021-11-23 12:40 UTC
The game for some reason permanently freezes when I try to stop recording with Nvidia Shadowplay. It only happens when ZHMModSDK is installed.

**Comment by OrfeasZ** [comment] 2022-01-30 20:04
I am unable to reproduce this on the latest version of the game (`3.100.0.0`) with the latest SDK version (`1.5.0`). Could you try again and see if this still happens to you?

**Comment by LikonLikon** [comment] 2022-01-31 11:02
Still happens on the latest version of the game and the latest SDK version. Maybe it has something to do with Shadowplay. I don't remember this happening with OBS so I'll give it another chance.

**Comment by LikonLikon** [comment] 2022-02-01 11:15
ZHMModSDK is the only mod that loads with the game.
I've disabled Epic games in-game overlay. Didn't fix the problem.
I even did a fresh Windows 10 install for different reasons.

**Comment by Deji69** [comment] 2022-03-11 22:10
I actually get this issue too with no mods, so I don't believe it's caused by this mod. Still an annoying issue I'd be happy to find a fix for.

**Comment by OrfeasZ** [comment] 2022-10-10 03:12
Closing this for now since I'm still unable to reproduce. If you are still having this issue with the latest SDK leave a comment.

**Closed by OrfeasZ** 2022-10-10 03:12 UTC
Labels: bug, help wanted
