### ISSUE TITLE
Editor mod can´t deselect glitch

### ISSUE THREAD

**Issue by GodPowerYT** [OrfeasZ/ZHMModSDK#107] opened 2024-05-18 15:25 UTC
for me if i click on a thing in mod menu with editor mod on it can`t be deselected at first this is not annoying but if you close the blue outline will still be there it could be fic´xed if you make it invisible if the mod menu is not open or just fix it all

**Comment by OrfeasZ** [comment] 2024-05-18 16:41
Duplicate of #106

**Closed by OrfeasZ** 2024-05-18 16:41 UTC
